/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
/*
 * MOVIES.java
 *
 * Created on Jun 17, 2019, 9:06:37 AM
 */

/**
 *
 * @author Student
 */
public class MOVIES extends javax.swing.JFrame {

    /** Creates new form MOVIES */
    public MOVIES() {
        initComponents();
    }
    String Email, Time, Theatre, Movie;
    public MOVIES(String a)
    {
        initComponents();
        this.Email = a;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb3 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cb4 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("Cinepolis, Seasons Mall, Pune");

        b3.setText("08:30 AM");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setText("09:00 PM");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b4.setText("12:00 PM");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b1.setText("08:00 AM");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("PVR, Kumar Pacific Mall, Pune");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Date:");

        bg1.add(cb3);
        cb3.setFont(new java.awt.Font("Calibri", 1, 18));
        cb3.setText("Student Of The Year 2");

        bg1.add(cb2);
        cb2.setFont(new java.awt.Font("Calibri", 1, 18));
        cb2.setText("John Wick: Chapter 3");

        bg1.add(cb1);
        cb1.setFont(new java.awt.Font("Calibri", 1, 18));
        cb1.setText("Avengers: Endgame");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Now Showing:-");

        bg1.add(cb4);
        cb4.setFont(new java.awt.Font("Calibri", 1, 18));
        cb4.setText("The Tashkent Files");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Endgame.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SOTY 2.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/The Tashkent Files.jpg"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("DD-MM-YYYY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cb1)
                        .addGap(61, 61, 61)
                        .addComponent(cb2)
                        .addGap(65, 65, 65)
                        .addComponent(cb3)
                        .addGap(76, 76, 76)
                        .addComponent(cb4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1)
                                .addGap(26, 26, 26)
                                .addComponent(b2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7))
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b3)
                                .addGap(28, 28, 28)
                                .addComponent(b4))
                            .addComponent(jLabel10))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, 0, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb2)
                        .addComponent(cb3)
                        .addComponent(cb4))
                    .addComponent(cb1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1)
                            .addComponent(b2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b3)
                            .addComponent(b4))))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
            String Date = tf1.getText();
            if(cb1.isSelected()||cb2.isSelected()||cb3.isSelected()||cb4.isSelected())
            {
                if(cb1.isSelected())
                Movie = "Avengers: Endgame";
                else if(cb2.isSelected())
                Movie = "John Wick: Chapter 3";
                else if(cb3.isSelected())
                Movie = "Student Of The Year 2";
                else if(cb4.isSelected())
                Movie = "The Tashkent Files";
                if(Date.trim().isEmpty())
                    JOptionPane.showMessageDialog(null, "Enter the Date on which you want to watch the movie.");
                else if(Date.length() != 10)
                {
                    JOptionPane.showMessageDialog(null, "The Date You've entered doesn't match the \"DD-MM-YYYY\" format");
                    tf1.setText("");
                }
                else
                {
                Time = "08:30 AM";
                Theatre = "Cinepolis, Seasons Mall,Pune";
                new Seats(Email, Movie, Date, Time, Theatre).setVisible(true);
                this.setVisible(false);
                }
            }
            else
            JOptionPane.showMessageDialog(null, "Select the movie you want to watch.");
}//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
            String Date = tf1.getText();
            if(cb1.isSelected()||cb2.isSelected()||cb3.isSelected()||cb4.isSelected())
            {
                if(cb1.isSelected())
                Movie = "Avengers: Endgame";
                else if(cb2.isSelected())
                Movie = "John Wick: Chapter 3";
                else if(cb3.isSelected())
                Movie = "Student Of The Year 2";
                else if(cb4.isSelected())
                Movie = "The Tashkent Files";
                if(Date.trim().isEmpty())
                    JOptionPane.showMessageDialog(null, "Enter the Date on which you want to watch the movie.");
                else if (Date.length() != 10)
                {
                    JOptionPane.showMessageDialog(null, "The Date You've entered doesn't match the \"DD-MM-YYYY\" format");
                }
                else
                {
                Time = "09:00 PM";
                Theatre = "PVR, Kumar Pacific Mall,Pune";
                new Seats(Email, Movie, Date, Time, Theatre).setVisible(true);
                this.setVisible(false);
                }
            }
            else
            JOptionPane.showMessageDialog(null, "Select the movie you want to watch.");

}//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
            String Date = tf1.getText();
            if(cb1.isSelected()||cb2.isSelected()||cb3.isSelected()||cb4.isSelected())
            {
                if(cb1.isSelected())
                Movie = "Avengers: Endgame";
                else if(cb2.isSelected())
                Movie = "John Wick: Chapter 3";
                else if(cb3.isSelected())
                Movie = "Student Of The Year 2";
                else if(cb4.isSelected())
                Movie = "The Tashkent Files";
                if(Date.trim().isEmpty())
                    JOptionPane.showMessageDialog(null, "Enter the Date on which you want to watch the movie.");
                else if(Date.length()!= 10)
                {
                    JOptionPane.showMessageDialog(null, "The Date You've entered doesn't match the \"DD-MM-YYYY\" format");
                }
                else
                {
                Time = "12:00 PM";
                Theatre = "Cinepolis, Seasons Mall,Pune";
                new Seats(Email, Movie, Date, Time, Theatre).setVisible(true);
                this.setVisible(false);
                }
            }
            else
            JOptionPane.showMessageDialog(null, "Select the movie you want to watch.");
}//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
            String Date = tf1.getText();
            if(cb1.isSelected()||cb2.isSelected()||cb3.isSelected()||cb4.isSelected())
            {
                if(cb1.isSelected())
                Movie = "Avengers: Endgame";
                else if(cb2.isSelected())
                Movie = "John Wick: Chapter 3";
                else if(cb3.isSelected())
                Movie = "Student Of The Year 2";
                else if(cb4.isSelected())
                Movie = "The Tashkent Files";
                if(Date.trim().isEmpty())
                    JOptionPane.showMessageDialog(null, "Enter the Date on which you want to watch the movie.");
                else if(Date.length()!= 10)
                {
                    JOptionPane.showMessageDialog(null, "The Date You've entered doesn't match the \"DD-MM-YYYY\" format");
                }
                else
                {
                Time = "08:00 AM";
                Theatre = "PVR, Kumar Pacific Mall,Pune";
                new Seats(Email, Movie, Date, Time, Theatre).setVisible(true);
                this.setVisible(false);
                }
            }
            else
            JOptionPane.showMessageDialog(null, "Select the movie you want to watch.");
}//GEN-LAST:event_b1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MOVIES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables

}
